name: Java
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4
    - name: list workspace contents
      run: ls -al ${{ github.workspace }}
    - name: Setup Java and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'
    - name: Package the Application
      run: |
        mvn -B package
        ls -al ${{ github.workspace }}/target
