name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4
    - name: Setup Java and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'
    - name: Save Cache
      uses: actions/cache/save@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - name: Test the Application
      run: mvn test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4
    - name: Setup Java and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'
    - name: Restore Cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - name: Package the Application
      run: mvn -DskipTests=true package
